# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-27 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, b'INACTIVE'), (1, b'ACTIVE')], default=1, help_text=b'Category Status')),
                ('customer_name', models.CharField(blank=True, help_text=b'Customer Name', max_length=128, null=True)),
                ('mobile_no', models.CharField(blank=True, help_text=b'Customer Mobile NO', max_length=512, null=True)),
                ('email_id', models.EmailField(blank=True, help_text=b'Customer Email', max_length=128, null=True)),
                ('customer_message', models.TextField(blank=True, help_text=b'Customer Message', null=True)),
                ('remarks', models.TextField(blank=True, help_text=b'Customer Feedback', null=True)),
                ('contact_status', models.IntegerField(choices=[(0, b'Not Contacted'), (1, b'Contacted'), (1, b'Interested'), (1, b'Not Interested')], default=0, help_text=b'Contact Status')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
